channels:
  - conda-forge
  - bioconda
  - r
dependencies:
  - adapterremoval=2.3.1
  - argcomplete=1.12.1
  - argparse=1.4.0
  - biopython=1.77
  - bowtie2=2.3.5.1
  - dedup=0.12.5
  - pandas=1.0.3
  - pip=19.3.1
  - pysam=0.15.3
  - python=3.6.7
  - r-Rcpp=1.0.4.6
  - r-RcppGSL=0.3.8
  - r-gam=1.16.1
  - r-ggplot2=3.3.0
  - r-inline=0.3.15
  - rsync=3.1.3
  - requests=2.24.0
  - samtools=1.9
  - scipy=1.4.1
  - seqkit=0.13.2
  - seqtk=1.3
  - snakefmt=0.2.2
  - snakemake=5.20.1
  - sra-tools=2.9.1
  - wget=1.20.1
  - pip:
      - git+git://github.com/ginolhac/mapDamage.git@31f8dd1800b61a3e29375531e01a3e3fb115dc79
