# `haystac config` defaults
cache:
  ~/haystac/cache/
mismatch_probability:
  0.05
bowtie2_scaling:
  25.0
use_conda:
  True

# `haystac database` defaults
rank:
  'species'
seed:
  null
cores:
  all
mem:
  all

# `haystac sample` defaults
collapse:
  False
trim_adapters:
  True
min_prob:
  0.75